highlighter: rouge
github: [Repository metadata]
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
  - "s3_website.yml"
  # We want to include vendor files at root but not those in sub dirs
  - "vendor/**/*"
# source:	_src
url: http://test.atlb.us
title: ATLtransit
# gems:
  # - jekyll-sitemap

prose:
  rooturl: pages
  media: assets/images

collections:
  agencies:
    output: true
    permalink: /about/agencies/:path/
    name: agencies
  services:
    output: true
    permalink: /about/services/:path/
    name: services
  # - fares
  # fares:
  #   output: true
  #   permalink: /fares/:path/
  # tools:
  # 	output: true
  # 	permalink: /tools/:path/