highlighter: pygments
github: [Repository metadata]
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
# source:	_src
url: http://test.atlb.us
title: atltransit
gems:
  - jekyll-sitemap

prose:
  rooturl: /pages
  media: /build/images

collections:
  agencies:
    output: true
    permalink: /about/agencies/:path/
    name: agencies
  services:
    output: true
    permalink: /about/services/:path/
    name: services
  # - fares
  # fares:
  #   output: true
  #   permalink: /fares/:path/
  # tools:
  # 	output: true
  # 	permalink: /tools/:path/